version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
  
  backend:
    image: prodgeti/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  
  frontend:
    env_file: .env
    image: prodgeti/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    image: prodgeti/foodgram_nginx:latest
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media