TAG_MAX_LENGTH = 32
INGR_MAX_LENGTH = PASSWORD_MAX_LENGTH = 128
MEASURMENT_MAX_LENGTH = 64
FIRST_NAME_MAX_LENGTH = LAST_NAME_MAX_LENGTH = USERNAME_MAX_LENGTH = 150
RECIPE_MAX_LENGTH = 256

MIN_TIME = MIN_AMOUNT = 1
MAX_TIME = MAX_AMOUNT = 32000

PAGE_SIZE = 16
