TAG_LENGTH = 56
INGR_LENGTH = 100
MEASURMENT_LENGTH = 64
FIRST_NAME_LENGTH = LAST_NAME_LENGTH = USERNAME_LENGTH = 150
RECIPE_MAX_LENGTH = 256

MIN_TIME = MIN_AMOUNT = 1
MAX_TIME = MAX_AMOUNT = 32000

PAGE_SIZE = 16
